.TH PULSEVIEW 1 "May 1, 2013"
.SH "NAME"
PulseView \- Qt-based LA/scope/MSO GUI for sigrok
.SH "SYNOPSIS"
.B pulseview \fR[\fB\-h?V\fR] [\fB\-h\fR|\fB\-?\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR]
.SH "DESCRIPTION"
.B PulseView
is a cross-platform Qt-based GUI for the
.B sigrok
software suite for test and measurement equipment such as logic analyzers,
oscilloscopes, MSOs, and more.
.SH "OPTIONS"
.B PulseView
has very few command line options, as most configuration elements are
available from the GUI itself.
.TP
.B "\-h, \-?, \-\-help"
Show a help text and exit.
.TP
.B "\-V, \-\-version"
Show version information and exit.
.SH "EXIT STATUS"
.B PulseView
exits with 0 on success, 1 on most failures.
.SH "SEE ALSO"
\fBsigrok\-cli\fP(1)
.SH "BUGS"
Please report any bugs via Bugzilla
.RB "(" http://sigrok.org/bugzilla ")"
or on the sigrok\-devel mailing list
.RB "(" sigrok\-devel@lists.souceforge.net ")."
.SH "LICENSE"
.B PulseView
is covered by the GNU General Public License (GPL), version 3 or later.
.SH "AUTHORS"
Please see the individual source code files.
.PP
This manual page was written by Uwe Hermann <uwe@hermann\-uwe.de>.
It is licensed under the terms of the GNU GPL (version 2 or later).
